name: Django application
on: 
  push:
      branches: [ "*" ]
  pull_request:
      branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: chichi
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis: 
        image: redis:latest
        ports:
          - 6379:6379
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # - name: Run isort
      #   uses: isort/isort-action@master
        
      # - name: Run black
      #   uses: psf/black@stable
      
      # - name: Run flake8
      #   run: flake8

      
      - name: Run database migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        run: pytest --disable-warnings
